from enum import Enum


class TenantStatus(str, Enum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"


class PersonRole(str, Enum):
    EMPLOYEE = "EMPLOYEE"
    MANAGER = "MANAGER"
    HR = "HR"
    ADMIN = "ADMIN"
    IT = "IT"
    SECURITY = "SECURITY"
    PROCUREMENT = "PROCUREMENT"
    FINANCE = "FINANCE"
    WORKPLACE = "WORKPLACE"
    OPERATOR = "OPERATOR"
    VENDOR_CONTACT = "VENDOR_CONTACT"


class LocationType(str, Enum):
    SITE = "SITE"
    FLOOR = "FLOOR"
    ZONE = "ZONE"
    ROOM = "ROOM"


class ResourceType(str, Enum):
    SEAT = "SEAT"
    CHAIR = "CHAIR"
    PARKING_SLOT = "PARKING_SLOT"
    LAPTOP = "LAPTOP"
    MONITOR = "MONITOR"
    ACCESS_CARD = "ACCESS_CARD"
    PEDESTAL = "PEDESTAL"


class ResourceStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    ALLOCATED = "ALLOCATED"
    RESERVED = "RESERVED"
    CONFLICT = "CONFLICT"
    MAINTENANCE = "MAINTENANCE"
    MISSING = "MISSING"
    RETIRED = "RETIRED"


class EventSource(str, Enum):
    GMAIL = "GMAIL"
    MANUAL = "MANUAL"
    API = "API"
    SYSTEM = "SYSTEM"


class ConversationStatus(str, Enum):
    OPEN = "OPEN"
    AWAITING_INFORMATION = "AWAITING_INFORMATION"
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"


class OutcomeStatus(str, Enum):
    DRAFT = "DRAFT"
    VALIDATING = "VALIDATING"
    ACTIVE = "ACTIVE"
    AT_RISK = "AT_RISK"
    BLOCKED = "BLOCKED"
    PARTIALLY_READY = "PARTIALLY_READY"
    READY = "READY"
    RESOLVED = "RESOLVED"
    VERIFIED = "VERIFIED"
    CLOSED = "CLOSED"
    REOPENED = "REOPENED"
    CANCELLED = "CANCELLED"
    ADMINISTRATIVELY_CLOSED = "ADMINISTRATIVELY_CLOSED"


class RequirementStatus(str, Enum):
    REQUIRED = "REQUIRED"
    NOT_REQUIRED = "NOT_REQUIRED"
    INFORMATION_MISSING = "INFORMATION_MISSING"
    ACTION_PENDING = "ACTION_PENDING"
    APPROVAL_PENDING = "APPROVAL_PENDING"
    COMPLETED = "COMPLETED"
    EXCEPTION = "EXCEPTION"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class TaskStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    ASSIGNED = "ASSIGNED"
    ACCEPTED = "ACCEPTED"
    IN_PROGRESS = "IN_PROGRESS"
    INFORMATION_REQUIRED = "INFORMATION_REQUIRED"
    APPROVAL_PENDING = "APPROVAL_PENDING"
    ON_HOLD = "ON_HOLD"
    COMPLETED_PENDING_EVIDENCE = "COMPLETED_PENDING_EVIDENCE"
    VERIFIED = "VERIFIED"
    CLOSED = "CLOSED"
    REOPENED = "REOPENED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"


class ApprovalDecision(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    DEFERRED = "DEFERRED"


class ExceptionSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ExceptionStatus(str, Enum):
    OPEN = "OPEN"
    IN_REVIEW = "IN_REVIEW"
    RESOLVED = "RESOLVED"
    WAIVED = "WAIVED"


class EvidenceStatus(str, Enum):
    SUBMITTED = "SUBMITTED"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"


class CommunicationType(str, Enum):
    ACTION_REQUIRED = "ACTION_REQUIRED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    INFORMATION_REQUIRED = "INFORMATION_REQUIRED"
    INFORMATION_ONLY = "INFORMATION_ONLY"
    AT_RISK = "AT_RISK"
    ESCALATION = "ESCALATION"
    COMPLETED = "COMPLETED"


class JobStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    DEAD_LETTER = "DEAD_LETTER"
    CANCELLED = "CANCELLED"


class JobType(str, Enum):
    PROCESS_EMAIL = "PROCESS_EMAIL"
    AI_EXTRACT = "AI_EXTRACT"
    CLARIFY = "CLARIFY"
    OUTCOME_ORCHESTRATE = "OUTCOME_ORCHESTRATE"
    SEND_NOTIFICATION = "SEND_NOTIFICATION"
    RETRY = "RETRY"


class ProcessingStage(str, Enum):
    INTAKE = "INTAKE"
    IDEMPOTENCY = "IDEMPOTENCY"
    QUEUED = "QUEUED"
    AI_INTERPRETATION = "AI_INTERPRETATION"
    SCHEMA_VALIDATION = "SCHEMA_VALIDATION"
    CONTEXT_RETRIEVAL = "CONTEXT_RETRIEVAL"
    RULES = "RULES"
    OUTCOME_ENGINE = "OUTCOME_ENGINE"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    COMMUNICATION = "COMMUNICATION"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ConfidenceRoute(str, Enum):
    AUTO = "AUTO"
    OPERATOR_REVIEW = "OPERATOR_REVIEW"
    CLARIFICATION = "CLARIFICATION"
    HUMAN_REQUIRED = "HUMAN_REQUIRED"


class InvoiceMatchStatus(str, Enum):
    MATCHED = "MATCHED"
    QUANTITY_MISMATCH = "QUANTITY_MISMATCH"
    RATE_MISMATCH = "RATE_MISMATCH"
    MISSING_PO = "MISSING_PO"
    MISSING_RECEIPT = "MISSING_RECEIPT"
    DUPLICATE = "DUPLICATE"
    VENDOR_MISMATCH = "VENDOR_MISMATCH"
    BANK_CHANGE_FLAGGED = "BANK_CHANGE_FLAGGED"
    PENDING_REVIEW = "PENDING_REVIEW"


class VendorStatus(str, Enum):
    ACTIVE = "ACTIVE"
    UNDER_REVIEW = "UNDER_REVIEW"
    SUSPENDED = "SUSPENDED"
    BLACKLISTED = "BLACKLISTED"


class AllegationStatus(str, Enum):
    UNVERIFIED = "UNVERIFIED"
    UNDER_REVIEW = "UNDER_REVIEW"
    SUBSTANTIATED = "SUBSTANTIATED"
    UNSUBSTANTIATED = "UNSUBSTANTIATED"


class AuditAction(str, Enum):
    EMAIL_RECEIVED = "EMAIL_RECEIVED"
    EMAIL_DEDUPLICATED = "EMAIL_DEDUPLICATED"
    AI_EXTRACTION_COMPLETED = "AI_EXTRACTION_COMPLETED"
    AI_REVIEW_REQUIRED = "AI_REVIEW_REQUIRED"
    OUTCOME_CREATED = "OUTCOME_CREATED"
    OUTCOME_UPDATED = "OUTCOME_UPDATED"
    TASK_CREATED = "TASK_CREATED"
    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_BLOCKED = "TASK_BLOCKED"
    TASK_STATUS_CHANGED = "TASK_STATUS_CHANGED"
    TASK_COMPLETED = "TASK_COMPLETED"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_GRANTED = "APPROVAL_GRANTED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    VENDOR_CONTACTED = "VENDOR_CONTACTED"
    EVIDENCE_ADDED = "EVIDENCE_ADDED"
    EVIDENCE_VERIFIED = "EVIDENCE_VERIFIED"
    OUTCOME_VERIFIED = "OUTCOME_VERIFIED"
    OUTCOME_CLOSED = "OUTCOME_CLOSED"
    AUTOMATION_FAILED = "AUTOMATION_FAILED"
    AUTOMATION_RETRIED = "AUTOMATION_RETRIED"
    HUMAN_OVERRIDE = "HUMAN_OVERRIDE"
    CLARIFICATION_SENT = "CLARIFICATION_SENT"
    INFORMATION_MERGED = "INFORMATION_MERGED"
    EXCEPTION_CREATED = "EXCEPTION_CREATED"
    COMMUNICATION_SENT = "COMMUNICATION_SENT"
    JOB_DEAD_LETTER = "JOB_DEAD_LETTER"
